import * as Redux from "redux";
import {
    IReactVaporState,
    tablesReducer,
    lastUpdatedCompositeReducer,
    filterBoxesReducer,
    facetsReducer,
    perPageCompositeReducer,
    paginationCompositeReducer,
    loadingsReducer,
    promptsReducer,
    actionBarsReducer,
    dropdownsReducer,
    dropdownsSearchReducer,
    flatSelectsReducer,
    tableRowsReducer,
    itemFiltersReducer,
    optionsCyclesReducer,
    optionPickersReducer,
    datePickersReducer,
    modalsReducer,
    subNavigationsReducer,
    tabGroupsReducer,
    toastsContainerReducer,
    tableHeaderCellsReducer,
    checkboxesReducer,
    inputsReducer
} from "react-vapor"
  
export const Reducers: Redux.Reducer<IReactVaporState> = Redux.combineReducers<IReactVaporState>({
    tables: tablesReducer,
    lastUpdatedComposite: lastUpdatedCompositeReducer,
    filters: filterBoxesReducer,
    facets: facetsReducer,
    perPageComposite: perPageCompositeReducer,
    paginationComposite: paginationCompositeReducer,
    loadings: loadingsReducer,
    prompts: promptsReducer,
    actionBars: actionBarsReducer,
    dropdowns: dropdownsReducer,
    dropdownSearch: dropdownsSearchReducer,
    flatSelect: flatSelectsReducer,
    rows: tableRowsReducer,
    itemFilters: itemFiltersReducer,
    optionsCycles: optionsCyclesReducer,
    optionPickers: optionPickersReducer,
    datePickers: datePickersReducer,
    modals: modalsReducer,
    subNavigations: subNavigationsReducer,
    tabs: tabGroupsReducer,
    toastContainers: toastsContainerReducer,
    tableHeaderCells: tableHeaderCellsReducer,
    checkboxes: checkboxesReducer,
    inputs: inputsReducer,
});